version: '3.1'

services:
    redis:
        container_name: nestify_redis
        image: 'redis:5.0.6'
        restart: always
        ports:
            - '63790:6379'
        networks:
            - app
    mongo:
        container_name: nestify_mongo    
        image: 'mongo:4.2'
        restart: always
        environment:
            MONGO_INITDB_DATABASE: nestify
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345678
        volumes:
            - ./.docker/mongodb-data:/data/db
            - ./scripts/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        ports:
            - '27017:27017'
        networks:
            - app
networks:
    app: