export const EVENT_BUS_OPTIONS = Symbol('EVENT_BUS_OPTIONS');
export const EVENT_BUS_SUBSCRIBER = Symbol('EVENT_BUS_SUBSCRIBER');
export const EVENT_BUS_LISTENER = Symbol('EVENT_BUS_LISTENER');
export const EVENT_BUS_ERROR = Symbol('EVENT_BUS_ERROR');
