version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nest-ddd-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestify
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: nest-ddd-app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: nestify
      APP_PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../src:/app/src
      - ../node_modules:/app/node_modules

volumes:
  postgres_data:
