version: '3'

services:
    redis:
        image: 'redis:alpine'
        restart: always
        ports:
            - '6379:6379'
        networks:
            - app

    postgres:
        image: postgres:9.6
        restart: always
        environment:
            POSTGRES_PASSWORD: 123456
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - app

    rabbitmq:
        image: rabbitmq:management-alpine
        restart: always
        ports:
            - '15672:15672'
            - '5672:5672'
        networks:
            - app

    # elasticsearch:
    #     image: elasticsearch:5.6
    #     restart: always
    #     ports:
    #         - '9200'
    #         - '9300'
    #     networks:
    #         - app
    # influxdb:
    #     image: influxdb
    #     restart: always
    #     ports:
    #         - '8086'
    #         - '8083'
    #     networks:
    #         - app
    # app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - '3000'
    #     volumes:
    #         - .:/code
    #     networks:
    #         - app

networks:
    app:

volumes:
    db-data:
    es-data:
